import * as cron from 'node-cron';
import { MarketEventsService } from './market-events.service';
import { aiService } from './ai.service';
import debug from 'debug';

const log = debug('market-events:scheduler');

export class SchedulerService {
  private marketEventsService: MarketEventsService;
  private isRunning: boolean = false;

  constructor() {
    this.marketEventsService = new MarketEventsService();
  }

  /**
   * Generate events for current week on startup (only if none exist)
   */
  async generateCurrentWeekEvents(): Promise<void> {
    try {
      log('Checking current week events on startup...');

      // Check if current week events already exist
      const existingEvents = await this.marketEventsService.getCurrentWeekEvents();

      if (existingEvents.length > 0) {
        log(`Current week events already exist (${existingEvents.length} events). Skipping generation.`);
        return;
      }

      log('Generating events for current week on startup...');
      const events = await aiService.generateWeeklyMarketEvents(); // Current week
      const result = await this.marketEventsService.createEvents(events);

      log(`Successfully created ${result.created.length} current week events (${result.skipped} skipped)`);
    } catch (error) {
      log('Error generating current week events:', error);
      throw error;
    }
  }

  /**
   * Start the scheduled job for generating weekly market events
   * Runs every Sunday at 9:00 AM to generate events for the upcoming week
   */
  startWeeklyEventGeneration(): void {
    const cronExpression = process.env.EVENT_GENERATION_CRON || '0 9 * * 0'; // Default: Every Sunday at 9:00 AM

    log(`Starting weekly upcoming event generation with cron: ${cronExpression}`);

    cron.schedule(cronExpression, async () => {
      if (this.isRunning) {
        log('Weekly event generation already running, skipping...');
        return;
      }

      try {
        this.isRunning = true;
        log('Starting upcoming week market events generation...');

        await this.generateUpcomingWeekEvents();

        log('Upcoming week market events generation completed successfully');
      } catch (error) {
        log('Error in upcoming week event generation:', error);
      } finally {
        this.isRunning = false;
      }
    });

    log('Weekly upcoming event generation scheduler started');
  }

  /**
   * Generate events for the upcoming week (next week)
   */
  async generateUpcomingWeekEvents(): Promise<void> {
    try {
      log('Generating events for upcoming week...');

      const nextWeekStart = this.getNextWeekStart();
      const events = await aiService.generateWeeklyMarketEvents(nextWeekStart);
      const result = await this.marketEventsService.createEvents(events);

      log(`Successfully created ${result.created.length} upcoming week events (${result.skipped} skipped)`);
    } catch (error) {
      log('Error generating upcoming week events:', error);
      throw error;
    }
  }

  /**
   * Manually trigger event generation (for testing or immediate generation)
   */
  async generateWeeklyEvents(weekStart?: Date): Promise<void> {
    try {
      log('Generating weekly market events...');

      // Generate events using AI
      const events = await aiService.generateWeeklyMarketEvents(weekStart);

      if (events.length === 0) {
        log('No events generated by AI service');
        return;
      }

      // Store events in database (allow duplicates for manual generation)
      const result = await this.marketEventsService.createEvents(events);

      log(`Successfully created ${result.created.length} market events for the week (${result.skipped} skipped)`);
    } catch (error) {
      log('Error generating weekly events:', error);
      throw error;
    }
  }

  /**
   * Stop the scheduler (mainly for testing)
   */
  stop(): void {
    cron.getTasks().forEach(task => task.destroy());
    log('Scheduler stopped');
  }

  /**
   * Get the start date of the next week (Sunday)
   */
  private getNextWeekStart(): Date {
    const today = new Date();
    const nextSunday = new Date(today);
    nextSunday.setDate(today.getDate() + (7 - today.getDay()));
    return nextSunday;
  }
}

// Export singleton instance
export const schedulerService = new SchedulerService();
